### PR TITLE
minimal mermaid advection solver demo

### PR DESCRIPTION
**Pull request by sonic1sonic**

### CODE REVIEW

**Comment by ebrahimebrahim** [comment]
Thanks for the contribution! A few things:

- Since SimpleITK is now a dependency of the project, it should be included in `requirements.txt`
- Git is not good for large files. It can make the repository unwieldy, and it quickly brings us close to the 100MB github repository limit. Better to put the files somewhere they can be downloaded, then include a download link to them in the readme. If you make this change, then you'll want to amend your current commit rather than just add a new commit, otherwise the large files will stay inside the repository history and continue to bloat it. If you end up amending a commit then you might have to use `--force` when you push, .e.g `git push origin sample-OAI-loader --force`, in order to rewrite the branch's history on github.
- I get an error when I run the code:
```txt
Using default value = True for key = use_odeint of category = root.env
Using default value = False for key = use_ode_tuple of category = root.env
the param of smoother is <mermaid.smoother_factory.MultiGaussianFourierSmoother object at 0x7f1f262fc850>
Using default value = 1 for key = spline_order of category = root
Traceback (most recent call last):
  File "simple_oai_loader_demo.py", line 73, in <module>
    phi = adv_solver(init_phi.permute(0, 4, 1, 2, 3), None)
  File "/home/ebrahim/vsvf-monai/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ebrahim/vsvf-monai/venv/lib/python3.8/site-packages/mermaid/registration_networks.py", line 1671, in forward
    v = self.smoother.smooth(self.m, None, pars_to_pass_s, variables_from_optimizer,
  File "/home/ebrahim/vsvf-monai/venv/lib/python3.8/site-packages/mermaid/smoother_factory.py", line 237, in smooth
    Sv[:] = self.apply_smooth(v,vout,pars,variables_from_optimizer, smooth_to_compute_regularizer_energy, clampCFL_dt)    # here must use :, very important !!!!
  File "/home/ebrahim/vsvf-monai/venv/lib/python3.8/site-packages/mermaid/smoother_factory.py", line 463, in apply_smooth
    self._create_filter()
  File "/home/ebrahim/vsvf-monai/venv/lib/python3.8/site-packages/mermaid/smoother_factory.py", line 655, in _create_filter
    g = self.multi_gaussian_weights[nr] * utils.compute_normalized_gaussian(centered_id, mus, stds)
  File "/home/ebrahim/vsvf-monai/venv/lib/python3.8/site-packages/mermaid/utils.py", line 351, in compute_normalized_gaussian
    g = np.exp(-np.power(X[0,:, :, :] - mu[0], 2.) / (2 * np.power(sig[0], 2.))
IndexError: too many indices for array: array is 2-dimensional, but 4 were indexed
```

**Comment by sonic1sonic** [comment]
Thanks for the feedback!

- After checking my mermaid version, turned out I compiled mermaid from source (same as what easyreg does), and if I use `pip install mermaid` I got the same error. Might need to check with the maintainers of the mermaid library about this.

- Unfortunately, I don't have any file hosting service I can access to follow the best practice of storing the images on cloud and write a `download.sh` in the repo (I couldn't get `wget [google drive share link]` work). Do you have such resource on your end so we can do it in the `download.sh` way?

**Comment by ebrahimebrahim** [comment]
For downloading files from google drive we could use [gdown](https://github.com/wkentaro/gdown), which is actually an optional MONAI dependency, so the right version can be included in the monai install via `pip install monai[gdown]`

Let me look into whether this works for google drive links...

**Comment by ebrahimebrahim** [comment]
I think gdown should work, and you can do it from python within the demo script, checking if the file exists first. Here is the simpler usage from the gdown readme:

```py
import gdown

url = 'https://drive.google.com/uc?id=0B9P1L--7Wd2vNm9zMTJWOGxobkU'
output = '20150428_collected_images.tgz'
gdown.download(url, output, quiet=False)
```

There are other approaches in the gdown readme that also validate md5 hash. If you wanted, you could use md5 hash to check whether the correct file already exists, to decide whether to download.

**Comment by sonic1sonic** [comment]
Cool! Thank you! I will implement a `gdown` version of doing so.

**Comment by ebrahimebrahim** [comment]
For the mermaid error, until `pip install mermaid` works we can just insert an instruction in the readme to clone the mermaid repository, like easyreg does. This is fine, I think, since we are just using mermaid for validation. It doesn't have to be used in the main demo, which will later become the tutorial.

**Comment by sonic1sonic** [comment]
Add `gdown` support and fix the mermaid smoother error. [3113123]( https://github.com/ebrahimebrahim/vsvf-monai/commit/3113123ac1d766f278df88ccb318c11855724c3a ) is ready for review now.

**Comment by ebrahimebrahim** [comment]
This is looking really good, and it ran perfectly for me this time!
Looking through code now

**Review by ebrahimebrahim — APPROVED** [review]
Looks great!

**Pull request merged**
